version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: e-invoice
      POSTGRES_PASSWORD: e-invoice
      POSTGRES_DB: e-invoice
    ports:
      - 5432:5432
  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_LOGLEVEL: DEBUG
    ports:
      - 8080:8080
    #volumes:
     # - './realm/realm-export.json:/tmp/realm-export.json'
    command:
      #- import --dir /opt/keycloak/data/import
      - start-dev
